export const products = [
  {
    id: 1,
    name: "Detergente Líquido Citrus 3L",
    price: 6990,
    category: "Lavandería",
    image: "https://http2.mlstatic.com/D_NQ_NP_2X_856239-MLC80102091658_102024-F.webp",
  },
  {
    id: 2,
    name: "Cloro Gel Desinfectante 900ml",
    price: 2390,
    category: "Desinfección",
    image: "https://i5.walmartimages.cl/asr/0878ffb2-828b-492c-b9f9-52462c9ce370.14d2c288ab24ee15b40637ccff1f05f0.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF",
  },
  {
    id: 3,
    name: "Limpiavidrios Antimanchas 500ml",
    price: 3290,
    category: "Vidrios",
    image: "/src/assets/images/image-default.jpg",
  },
  {
    id: 4,
    name: "Desengrasante Cocina 750ml",
    price: 3790,
    category: "Cocina",
    image: "/src/assets/images/image-default.jpg",
  },
  {
    id: 5,
    name: "Multiuso Lavanda 1L",
    price: 2990,
    category: "Multiuso",
    image: "/src/assets/images/image-default.jpg",
  },
  {
    id: 6,
    name: "Limpiador Baño Antisarro 750ml",
    price: 3490,
    category: "Baño",
    image: "/src/assets/images/image-default.jpg",
  },
  {
    id: 7,
    name: "Jabón Líquido Manos Antibacterial 500ml",
    price: 2690,
    category: "Higiene",
    image: "/src/assets/images/image-default.jpg",
  },
  {
    id: 8,
    name: "Suavizante Concentrado 2L",
    price: 5990,
    category: "Lavandería",
    image: "/src/assets/images/image-default.jpg",
  },
  {
    id: 9,
    name: "Pastillas Lavavajillas 30u",
    price: 8990,
    category: "Cocina",
    image: "/src/assets/images/image-default.jpg",
  },
];
