export const products = [
  {
    id: 1,
    title: "Detergente Líquido Citrus 3L",
    price: 6990,
    category: "Lavandería",
    thumbnail: "https://http2.mlstatic.com/D_NQ_NP_2X_856239-MLC80102091658_102024-F.webp",
    shortDescription: "Detergente líquido concentrado para lavado diario, aroma cítrico y alto rendimiento.",
    rating: 4.5,
    stock: 50,
    brand: "CleanLosRios",
  },
  {
    id: 2,
    title: "Cloro Gel Desinfectante 900ml",
    price: 2390,
    category: "Desinfección",
    thumbnail: "https://i5.walmartimages.cl/asr/0878ffb2-828b-492c-b9f9-52462c9ce370.14d2c288ab24ee15b40637ccff1f05f0.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF",
    shortDescription: "Cloro gel para desinfectar superficies, práctico y de fácil aplicación.",
    rating: 4.5,
    stock: 50,
    brand: "Clorinda",
  },
  {
    id: 3,
    title: "Limpiavidrios Antimanchas 500ml",
    price: 3290,
    category: "Vidrios",
    thumbnail: "/src/assets/images/image-default.jpg",
    shortDescription: "Limpia vidrios y espejos sin dejar marcas, secado rápido.",
    rating: 4.5,
    stock: 50,
    brand: "CleanLosRios",
  },
  {
    id: 4,
    title: "Desengrasante Cocina 750ml",
    price: 3790,
    category: "Cocina",
    thumbnail: "/src/assets/images/image-default.jpg",
    shortDescription: "Desengrasa hornos y encimeras, ideal para grasa difícil en cocina.",
    rating: 4.5,
    stock: 50,
    brand: "CleanLosRios",
  },
  {
    id: 5,
    title: "Multiuso Lavanda 1L",
    price: 2990,
    category: "Multiuso",
    thumbnail: "/src/assets/images/image-default.jpg",
    shortDescription: "Multiuso lavanda",
    rating: 4.5,
    stock: 50,
    brand: "CleanLosRios",
  },
  {
    id: 6,
    title: "Limpiador Baño Antisarro 750ml",
    price: 3490,
    category: "Baño",
    thumbnail: "/src/assets/images/image-default.jpg",
    shortDescription: "Producto aún sin descripción",
    rating: 4.5,
    stock: 50,
    brand: "CleanLosRios",
  },
  {
    id: 7,
    title: "Jabón Líquido Manos Antibacterial 500ml",
    price: 2690,
    category: "Higiene",
    thumbnail: "/src/assets/images/image-default.jpg",
    shortDescription: "Producto aún sin descripción",
    rating: 4.5,
    stock: 50,
    brand: "CleanLosRios",
  },
  {
    id: 8,
    title: "Suavizante Concentrado 2L",
    price: 5990,
    category: "Lavandería",
    thumbnail: "/src/assets/images/image-default.jpg",
    shortDescription: "Producto aún sin descripción",
    rating: 4.5,
    stock: 50,
    brand: "CleanLosRios",
  },
  {
    id: 9,
    title: "Pastillas Lavavajillas 30u",
    price: 8990,
    category: "Cocina",
    thumbnail: "/src/assets/images/image-default.jpg",
    shortDescription: "Producto aún sin descripción",
    rating: 4.5,
    stock: 50,
    brand: "CleanLosRios",
  },
];
